---
- name: get current ruby version
  command: ruby --version
  register: ruby_version
  ignore_errors: true

- name: install
  become: yes
  command: ruby-build {{ ruby_via_ruby_build.version }} /usr/local
  when: ruby_version.rc != 0 or ruby_version.stdout.find(ruby_via_ruby_build.version) == -1

- name: disable gem documentation
  become: yes
  copy: >
    content='gem: --no-document'
    dest=/usr/local/etc/gemrc
    mode=0644

- name: install bundler
  become: yes
  gem: name=bundler user_install=no state=present
